### ISSUE TITLE
upgrade to v0.6.0 & renaming of plugin to formvalidation

### ISSUE THREAD

**Issue by slavus** [webjars/bootstrapvalidator#4]
Please add v0.6.0.

Also from version 0.6.0 plugin has renamed to formvalidation.
http://formvalidation.io/news/v0.6.0-released/

Please rename (or create new one)  webjar to formvalidation
http://formvalidation.io

**Comment by jamesward** [comment]
I think a new WebJar would be good.  I'll add it to the queue.

**Comment by jamesward** [comment]
Filed at: https://github.com/webjars/webjars/issues/775
